"""Sync the conversational layer (references/topics/*.md) to the atom store.

Usage:  python -m engram topics <brain-dir>

For every topic, (re)writes an AUTO-INDEX block listing each atom under it — text, numbers, a
source proof link, type and confidence — grouped by type. The block sits between markers, so
hand-written narrative above it is preserved and re-running never drifts below the graph.

By default each topic gets its own file `<topic>.md`. A brain may provide
`references/topic_map.json` ({"topicName": "file.md", ...}) to merge several topics into one
file. Source links resolve from `sources/manifest.json` when present, else fall back to
youtu.be/<id> (the common case) or a bare code span.
"""
from __future__ import annotations

import json
import os
import re
import sys

from .core import Brain, require_brain

START = "<!-- AUTO-INDEX:START (generated by `python -m engram topics` — do not edit by hand) -->"
END = "<!-- AUTO-INDEX:END -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)

KIND_ORDER = ["claim", "concept", "definition", "method", "result", "number", "example",
              "analogy", "caveat", "product", "idea", "opinion", "warning", "prediction",
              "bio", "resource", "style"]


def _source_links(brain: Brain) -> dict:
    """source-id → markdown link, resolved from the manifest where possible."""
    links = {}
    man = brain.manifest()
    for item in man.get("items", []):
        sid, url = item.get("id"), item.get("url")
        if sid and url:
            links[sid] = f"[{sid}]({url})"
    return links


def _link_for(sid: str, links: dict) -> str:
    if sid in links:
        return links[sid]
    # default to YouTube (the dominant source) but degrade gracefully
    if re.fullmatch(r"[A-Za-z0-9_-]{11}", sid):
        return f"[{sid}](https://youtu.be/{sid})"
    return f"`{sid}`"


def main(argv: list[str]) -> int:
    brain = require_brain(argv[0] if argv else ".")
    if brain is None:
        return 2
    atoms = brain.atoms()
    links = _source_links(brain)

    topic_map = {}
    tm_path = os.path.join(brain.root, "references", "topic_map.json")
    if os.path.exists(tm_path):
        with open(tm_path, encoding="utf-8-sig") as f:
            topic_map = json.load(f)

    by_file: dict = {}
    for a in atoms:
        topic = a.get("topic", "misc")
        # basename() neutralizes any path separators / .. in a (possibly shared) topic_map.json
        fn = os.path.basename(topic_map.get(topic, f"{topic}.md")) or f"{topic}.md"
        by_file.setdefault(fn, []).append(a)

    os.makedirs(brain.topics_dir, exist_ok=True)
    total = 0
    for fn, recs in sorted(by_file.items()):
        groups: dict = {}
        for a in recs:
            groups.setdefault(a.get("type", "claim"), []).append(a)

        lines = [START,
                 f"## Atom index ({len(recs)} atoms, auto-generated from atoms.jsonl)",
                 "",
                 "_Every atom under this topic with its source proof link. "
                 "Regenerate with `python -m engram topics`._", ""]
        for kind in KIND_ORDER + [k for k in groups if k not in KIND_ORDER]:
            if kind not in groups:
                continue
            lines.append(f"### {kind} ({len(groups[kind])})")
            for a in groups[kind]:
                nums = f" ({'; '.join(a['numbers'])})" if a.get("numbers") else ""
                srcs = " ".join(_link_for(s, links) for s in a.get("sources", []))
                attr = "" if a.get("attribution", "creator") == "creator" else f" _({a['attribution']})_"
                lines.append(f"- **{a['text']}**{nums}{attr} — {srcs} `[{a.get('confidence', '')}]`")
            lines.append("")
        block = "\n".join(lines) + END

        path = os.path.join(brain.topics_dir, fn)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                text = f.read()
            text = BLOCK_RE.sub(block, text) if BLOCK_RE.search(text) \
                else text.rstrip() + "\n\n" + block + "\n"
        else:
            text = f"# {fn[:-3].replace('-', ' ').title()}\n\n{block}\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        total += len(recs)
        print(f"  synced {fn}: {len(recs)} atoms")

    print(f"total {total} atoms indexed across {len(by_file)} topic file(s)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
