"""Render a brain's interactive knowledge-graph HTML from its atom/edge store.

Usage:  python -m engram graph <brain-dir>

Computes a topic-clustered force layout in Python (a good warm start), then injects the data
into `graph_template.html` — a self-contained canvas visualization with live physics, search,
topic filtering, a glass detail panel, and full keyboard/touch support. The store is the only
source of truth; this is always regenerated by `build`, so the graph can never go stale.
"""
from __future__ import annotations

import collections
import html
import json
import math
import os
import random
import sys

from .core import Brain, require_brain, topic_colors

TEMPLATE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "graph_template.html")


def _layout(atoms: list, edges: list) -> dict:
    """Topic-clustered force-directed warm-start layout. Returns id -> [x, y]."""
    rng = random.Random(7)
    topic_n = collections.Counter(a["topic"] for a in atoms)
    topics = [t for t, _ in topic_n.most_common()]
    R = 900
    centers = {
        t: (R * math.cos(2 * math.pi * i / len(topics)),
            R * math.sin(2 * math.pi * i / len(topics)))
        for i, t in enumerate(topics)
    } if topics else {}

    pos = {}
    for a in atoms:
        cx, cy = centers.get(a["topic"], (0, 0))
        s = 60 + 10 * math.sqrt(topic_n[a["topic"]])
        pos[a["id"]] = [cx + rng.uniform(-s, s), cy + rng.uniform(-s, s)]

    SPACING, ids = 44.0, list(pos)
    cs, R2, SP2 = SPACING * 1.6, (SPACING * 2) ** 2, SPACING * SPACING
    for _ in range(110):
        disp = {k: [0.0, 0.0] for k in ids}
        grid = collections.defaultdict(list)
        for k in ids:
            P = pos[k]
            grid[(int(P[0] // cs), int(P[1] // cs))].append(k)
        for (gx, gy), cell in grid.items():
            neigh = []
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    neigh += grid.get((gx + dx, gy + dy), ())
            for i in cell:
                Pi = pos[i]; ax = ay = 0.0
                for j in neigh:
                    if j == i:
                        continue
                    Pj = pos[j]; ddx = Pi[0] - Pj[0]; ddy = Pi[1] - Pj[1]
                    d2 = ddx * ddx + ddy * ddy
                    if d2 < 1e-6:
                        ddx = rng.uniform(-1, 1); ddy = rng.uniform(-1, 1); d2 = 1.0
                    if d2 < R2:
                        f = SP2 / d2; ax += ddx * f; ay += ddy * f
                D = disp[i]; D[0] += ax * 0.45; D[1] += ay * 0.45
        for e in edges:
            p = pos[e["from"]]; q = pos[e["to"]]
            dx = q[0] - p[0]; dy = q[1] - p[1]; f = 0.008
            disp[e["from"]][0] += dx * f; disp[e["from"]][1] += dy * f
            disp[e["to"]][0] -= dx * f; disp[e["to"]][1] -= dy * f
        for a in atoms:
            cx, cy = centers.get(a["topic"], (0, 0)); P = pos[a["id"]]
            disp[a["id"]][0] += (cx - P[0]) * 0.01; disp[a["id"]][1] += (cy - P[1]) * 0.01
        for k in ids:
            dx, dy = disp[k]; m = math.hypot(dx, dy)
            if m > 26:
                dx *= 26 / m; dy *= 26 / m
            P = pos[k]; P[0] += dx; P[1] += dy
    return pos


def build(brain: Brain) -> str:
    """Generate graph.html for a brain. Returns the output path."""
    atoms = brain.atoms()
    edges = brain.edges()
    byid = {a["id"]: a for a in atoms}
    edges = [e for e in edges if e["from"] in byid and e["to"] in byid]

    deg = collections.Counter()
    for e in edges:
        deg[e["from"]] += 1
        deg[e["to"]] += 1

    colors = topic_colors(a["topic"] for a in atoms) if atoms else {}
    src_links = {}
    for item in brain.manifest().get("items", []):
        if item.get("id") and item.get("url"):
            src_links[item["id"]] = item["url"]

    pos = _layout(atoms, edges)
    nodes = [{
        "id": a["id"],
        "x": round(pos[a["id"]][0], 1), "y": round(pos[a["id"]][1], 1),
        "t": a["topic"], "ty": a["type"], "c": a.get("confidence", ""),
        "at": a.get("attribution", "creator"),
        "r": 2.5 + min(deg[a["id"]], 14) * 0.7,
        "s": a["sources"][0] if a.get("sources") else "",
        "u": src_links.get(a["sources"][0]) if a.get("sources") else "",
        "x2": html.escape(a["text"][:280]),
    } for a in atoms]
    links = [{"a": e["from"], "b": e["to"], "r": e["rel"]} for e in edges]

    data = json.dumps({
        "name": brain.name,
        "nodes": nodes, "edges": links, "colors": colors,
        "counts": {"atoms": len(atoms), "edges": len(edges), "topics": len(colors)},
    }, ensure_ascii=False)

    with open(TEMPLATE, encoding="utf-8") as f:
        tmpl = f.read()
    out = tmpl.replace("__DATA__", data).replace(
        "__TITLE__", html.escape(brain.name + " — Engram brain"))
    with open(brain.graph_path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"  graph: {len(atoms)} atoms + {len(edges)} edges -> {brain.graph_path}")
    return brain.graph_path


def main(argv: list[str]) -> int:
    brain = require_brain(argv[0] if argv else ".")
    if brain is None:
        return 2
    try:
        build(brain)
    except FileNotFoundError as exc:
        print(f"error: could not render graph — {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
